### ISSUE TITLE
fonts-config overrides local settings

### ISSUE THREAD

**Issue by moconnor1234** [openSUSE/fonts-config#11]
I'm trying to use IBM Plex Mono's Alternate stylistic set OpenType feature to get slashed zeroes. I have edited ~/.config/fontconfig/fonts.conf as described in this [Archwiki entry](https://wiki.archlinux.org/index.php/Font_configuration/Examples) but I can't seem to get fontconfig to change the zeroes this way. I've also tried editing the root local.conf file and that also does nothing. After asking this question on /r/linuxquestions one person tried it and replied that it worked for them. I assumed they were on a different distro so I decided to try a Solus install I use on my laptop. Sure enough, when I added the fonts.conf with the code from the wiki above in ~/.config/fontconfig/fonts.conf I get slashed zeroes on Solus. I've also had issues with OpenSUSE ignoring font substitution instructions I've put in ~/.config/fontconfig/fonts.conf which leads me to believe the issue must be OpenSUSE's fonts-config. I can't seem to isloate exactly which file I need to edit to get the desired results on OpenSUSE. I tried YAST and looking at OpenSUSE documentation and nothing seems to address this. Is this a bug or am I just editing the wrong file or what?

**Comment by marguerite** [comment]
@moconnor1234

fontconfig is not magic but computer science :-)

I installed ibm-plex-mono-font from openSUSE and debug the issue you met:

1. Don’t trust the internet trash but the manual. You don’t need the fontformat not_equal null test block, because it’s fontformat is always TrueType, this test is always true.

2. run “FC_DEBUG=4 fc-match -s ‘IBM Plex Mono’ > plex.txt” and search “fontfeatures”, it has been applied well.

So I think the reason might be:

1. You are actually not using “IBM Plex Mono” but “Droid Sans” or something in your console or some where else.

2. You are actually using “IBM Plex Mono Bold” which does not covered by the config you provided.

You should provide me the exact context you’re in. eg: all self made configurations. terminal emulator choice and etc.

**Comment by moconnor1234** [comment]
Thank you for taking the time to respond even though It's not clear fonts-config is causing the issue. 

1. I appreciate that. I removed that line from my config file.

I can say for sure that I have my text editor (Kate) and terminal emulator (Konsole) set to IBM Plex Mono. Here's a screenshot: 
![xeaz1Jv](https://user-images.githubusercontent.com/23420536/59059782-d2258d80-886d-11e9-9235-23c198f4837f.png)

However, I recently discovered that GTK apps do display the fontfeatures while QT based ones in KDE do not. Therefore, I don't think fonts-config has anything to do with this issue. I have reported it to KDE and they seem to have found the cause in QT. Sorry for not looking into this before posting here (I had only tested the font in QT based apps).
