### ISSUE TITLE
Twemoji Mozilla should also be rejected

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/fonts-config#15]
https://github.com/openSUSE/fonts-config/blob/cb5beacc49c53ec33c99c27313bb2a91367611a5/32-emoji-reject.conf#L8

Firefox 66 is using its internal Twemoji Mozilla fonts for emojis. It should be rejected the same way as EmojiOne Mozilla.

**Comment by marguerite** [comment]
Hi, I blacklisted EmojiOne Mozilla because EmojiOne itself is deprecated for Twemoji upstream.

In later version I also remove this limit, because EmojiOne’s development is mostly done and it’s a good font. I just blacklisted Noto Emoji because it’s black and white.

This project is to enable the usage of color emoji in openSUSE, not for personal choice. Although we do prefer Noto Color Emoji but just because it’s the known to be available one
